Rubocop
smilenannan/questionnaire pull request #2
Opened 2017-03-09 03:27 UTC by smilenannan

install rubocop

2017-03-09 03:29 UTC, NaotoOta requested changes
とりあえずdeviseが混ざってる

2017-03-09 03:29 UTC, NaotoOta commented on Gemfile
> +gem 'devise'
devise？

2017-03-09 03:29 UTC, NaotoOta commented on Gemfile
> +group :development do
testも

2017-03-09 03:29 UTC, NaotoOta commented on Gemfile
> +  gem 'rubocop', require: false
require: falseは意味わかって使ってる？

2017-03-09 04:02 UTC, smilenannan commented on Gemfile
> +  gem 'rubocop', require: false
コードの中でライブラリを使用したい時に、require ライブラリ名 と書く必要があるってことです。意味を理解せず、使ってました。
参考サイト:
http://stackoverflow.com/questions/4800721/bundler-what-does-require-false-in-a-gemfile-mean

2017-03-09 04:13 UTC, NaotoOta commented on Gemfile
> +  gem 'rubocop', require: false
それだとちょっとずれてるんだよなあ
もうちょっと調べてみて

2017-03-09 04:21 UTC, smilenannan commented on Gemfile
> +  gem 'rubocop', require: false
rubocopはターミナルでのみ使うものだからってことっすか？
参考サイト:
http://stackoverflow.com/questions/35004020/why-does-rubocop-recommend-require-false-in-gemfile

2017-03-12 15:08 UTC, NaotoOta commented
まだdeviceまざってるで
今回はいいけど（どうせ使うと思うから）気をつけてね
自分で差分ちゃんと見るように
git add -p

2017-03-12 15:11 UTC, merged