Admin home
smilenannan/questionnaire pull request #5
Opened 2017-03-10 08:34 UTC by smilenannan

Admins can log in. 
Admins go to admin_home page after signing in.
Admins can go to password_edit page after from admin_home page.

2017-03-12 15:12 UTC, NaotoOta commented
@smilenannan 
コンフリクト解消
あと多分

2017-03-14 11:26 UTC, NaotoOta requested changes

2017-03-14 11:26 UTC, NaotoOta commented on app/controllers/admins/home_controller.rb
> +  before_action :authenticate_admin!
Admins::BaseControllerってのを作ってそこで`before_action :authenticate_admin!`して
それを継承させる
https://github.com/FiNCDeveloper/online_works/blob/master/app/controllers/admins/base_controller.rb
参考

2017-03-14 11:26 UTC, NaotoOta commented on app/controllers/admins/sessions_controller.rb
> +end
使う？

2017-03-14 11:26 UTC, NaotoOta commented on config/initializers/devise.rb
> +>>>>>>> fc4a7d5f3c8b2063cfe8a920e87bbebf9a295f5d
コンフリクト解消できてないよ

2017-03-14 11:26 UTC, NaotoOta commented on test/fixtures/admins.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
テストはrspecでやるので一旦これ消しといて

2017-03-14 11:26 UTC, NaotoOta commented on test/models/admin_test.rb
> +require 'test_helper'
テストはrspecでやるので一旦これ消しといて

2017-03-14 16:25 UTC, smilenannan commented on app/controllers/admins/sessions_controller.rb
> +end
いらないっすね。見逃してました。

2017-03-14 16:38 UTC, smilenannan commented on app/controllers/admins/home_controller.rb
> +  before_action :authenticate_admin!
その手があったんですね。勉強になります。

2017-03-15 02:55 UTC, NaotoOta approved these changes

2017-03-15 02:55 UTC, merged